### PR TITLE
Simple bug fixes

### PR DESCRIPTION
**Pull request by nacloos**
Simple fix for action_space not defined in the newest versions of gym.
Simple fix in info.py to get all the environments.

### CODE REVIEW

**Comment by nacloos** [comment]
Some checks raised the following error:
ModuleNotFoundError: No module named 'scipy'

which is coming from neurogym.envs.spatialsuppressmotion.SpatialSuppressMotion.
The problem is that scipy is not specified in setup.py, and so it is not installed before running the tests.

**Review by gyyang — COMMENTED** [review]
Latest gym doesn't require action_space anymore? Is this change going to be backward compatible?

Checks show several tests failing, do you know why?

**Comment by nacloos** [comment]
In the latest gym, action_space is no more initialized to None in the base class Env. It has to be defined in the child classes.

My comment above is related to these failing tests.

**Comment by gyyang** [comment]
Let's take neurogym.envs.spatialsuppressmotion.SpatialSuppressMotion out of the set of envs used to run the tests then?

**Comment by nacloos** [comment]
Do I remove this env completely from the NATIVE_ALLOW_LIST in neurogym.envs.registration since it requires a library that is not a requirement of neurogym?

**Comment by nacloos** [comment]
This is what is used to get a list of all the environments when running the tests

**Comment by gyyang** [comment]
I think removing from NATIVE_ALLOW_LIST is fine for now. In the long run, we'll probably need to add a try-except to catch module not found errors

**Review by gyyang — APPROVED** [review]

**Pull request merged**
