### PR TITLE
Fix gym compatibility

### PR DESCRIPTION
**Pull request by nacloos**
Add new tests and fix ScheduleEnvs reset.

### CODE REVIEW

**Review by gyyang — COMMENTED** [review]
Is this backward compatible with (one example) older version of gym as well? I suppose so, but can we check by adding this to the github workflows?

I see that BaseEnv doesn't have reset method now, can you help me understand the implication? Thank you!

**Comment by nacloos** [comment]
I added older versions of gym to github workflows. Gym 0.24 introduces an env_checker that raises warnings or even errors when the obs returned by step is not contained in observation_space. I disabled it for now since it raised some errors in the tests (some envs will need a revision if we want to enable this env_checker).

**Comment by nacloos** [comment]
I commented out the reset function in BaseEnv since:
* It doesn't call gym.Env.reset and is not compatible with its signature
* It returns the entire output of step but reset should return only the ob
* TrialEnv already implements reset

**Review by gyyang — APPROVED** [review]
Looks good to me now, thanks!

**Pull request merged**
